server.port=8083
spring.application.name=booking-service
spring.cloud.openfeign.httpclient.hc5.enabled=true

# Database Configuration
spring.datasource.url=jdbc:h2:mem:bookingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret (Must match auth-service & event-service)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971

#  Enable CircuitBreaker in Spring Cloud OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true

#  Expose Actuator endpoints to monitor Circuit Breaker states
management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#  Configure Resilience4j Circuit Breaker Instance for 'event-service'
resilience4j.circuitbreaker.instances.eventServiceBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.eventServiceBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.eventServiceBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.eventServiceBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.eventServiceBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.eventServiceBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.eventServiceBreaker.automatic-transition-from-open-to-half-open-enabled=true